export const firstData = [
  '1',
  'English',
  'English Cruise',
  'S.Chand',
  'English Comprehension ',
  'S.Chand',
  'English Hand writing',
  'English-3',
  'Firefly',
  '2',
  'Maths',
  'New Learning Composite Maths',
  'S.Chand',
  '3',
  'EVS',
  'The Blue Planet',
  'Goyal',
  '4',
  'Tamil',
  'Tamil Samacheer',
  'Tamil Ilakkanam',
  'Tamil Amuthu Ilakkana Payirchi',
  'Tamil Handwriting',
  'Tamil-3',
  'Firefly',
  '5',
  'Hindi',
  'Goyal',
  '6',
  'Computer',
  'Fun With Coding',
  'Goyal',
  '7',
  'Drawing',
  'Canvas C',
  'Goyal',
  '8',
  'GK',
  'General Knowledge Times',
  'Goyal',
  '9',
  'Aptitude',
  'Know Your Aptitude',
  'Goyal'
]
export const secondData = [
  '1',
  'English',
  'English Cruise',
  'S.Chand',
  'English Comprehension ',
  'S.Chand',
  'English Hand writing',
  'English-3',
  'Firefly',
  '2',
  'Maths',
  'New Learning Composite Maths',
  'S.Chand',
  '3',
  'EVS',
  'The Blue Planet',
  'Goyal',
  '4',
  'Tamil',
  'Tamil Samacheer',
  'Tamil Ilakkanam',
  'Tamil Amuthu Ilakkana Payirchi',
  'Tamil Handwriting',
  'Tamil-3',
  'Firefly',
  '5',
  'Hindi',
  'Goyal',
  '6',
  'Computer',
  'Fun With Coding',
  'Goyal',
  '7',
  'Drawing',
  'Canvas C',
  'Goyal',
  '8',
  'GK',
  'General Knowledge Times',
  'Goyal',
  '9',
  'Aptitude',
  'Know Your Aptitude',
  'Goyal'
]
export const thirdData = [
  '1',
  'English',
  'English Cruise',
  'S.Chand',
  'English Comprehension ',
  'S.Chand',
  'English Hand writing',
  'English-4',
  'Firefly',
  'Grammar',
  'Roseway Grammar',
  '2',
  'Maths',
  'New Learning Composite Maths',
  'S.Chand',
  '3',
  'Science',
  'Science Mission',
  'S.Chand',
  '4',
  'Tamil',
  'Tamil Samacheer',
  'Tamil Ilakkanam',
  'Tamil Amuthu Ilakkana Payirchi',
  'Tamil Handwriting',
  'Tamil-4',
  'Firefly',
  '5',
  'Social',
  'Social Science Success',
  'Goyal',
  '6',
  'Hindi',
  'Goyal',
  '7',
  'Computer',
  'Fun With Coding',
  'Goyal',
  '8',
  'Drawing',
  'Canvas C',
  'Goyal',
  '9',
  'GK',
  'General Knowledge Times',
  'Goyal',
  '10',
  'Aptitude',
  'Know Your Aptitude',
  'Goyal'
]
export const fourthData = [
  '1',
  'English',
  'English Cruise',
  'S.Chand',
  'English Comprehension ',
  'S.Chand',
  'English Hand writing',
  'English-4',
  'Firefly',
  'Grammar',
  'Roseway Grammar',
  '2',
  'Maths',
  'New Learning Composite Maths',
  'S.Chand',
  '3',
  'Science',
  'Science Mission',
  'S.Chand',
  '4',
  'Tamil',
  'Tamil Samacheer',
  'Tamil Ilakkanam',
  'Tamil Amuthu Ilakkana Payirchi',
  'Tamil Handwriting',
  'Tamil-4',
  'Firefly',
  '5',
  'Social',
  'Social Science Success',
  'Goyal',
  '6',
  'Hindi',
  'Goyal',
  '7',
  'Computer',
  'Fun With Coding',
  'Goyal',
  '8',
  'Drawing',
  'Canvas C',
  'Goyal',
  '9',
  'GK',
  'General Knowledge Times',
  'Goyal',
  '10',
  'Aptitude',
  'Know Your Aptitude',
  'Goyal'
]
export const fifthData = [
  '1',
  'English',
  'English Cruise',
  'S.Chand',
  'English Comprehension ',
  'S.Chand',
  'English Hand writing',
  'English-3',
  'Firefly',
  '2',
  'Maths',
  'New Learning Composite Maths',
  'S.Chand',
  '3',
  'EVS',
  'The Blue Planet',
  'Goyal',
  '4',
  'Tamil',
  'Tamil Samacheer',
  'Tamil Ilakkanam',
  'Tamil Amuthu Ilakkana Payirchi',
  'Tamil Handwriting',
  'Tamil-3',
  'Firefly',
  '5',
  'Hindi',
  'Goyal',
  '6',
  'Computer',
  'Fun With Coding',
  'Goyal',
  '7',
  'Drawing',
  'Canvas C',
  'Goyal',
  '8',
  'GK',
  'General Knowledge Times',
  'Goyal',
  '9',
  'Aptitude',
  'Know Your Aptitude',
  'Goyal'
]
export const sixData = [
  '1',
  'English',
  'English Cruise',
  'S.Chand',
  'English Comprehension ',
  'S.Chand',
  'English Hand writing',
  'English-3',
  'Firefly',
  '2',
  'Maths',
  'New Learning Composite Maths',
  'S.Chand',
  '3',
  'EVS',
  'The Blue Planet',
  'Goyal',
  '4',
  'Tamil',
  'Tamil Samacheer',
  'Tamil Ilakkanam',
  'Tamil Amuthu Ilakkana Payirchi',
  'Tamil Handwriting',
  'Tamil-3',
  'Firefly',
  '5',
  'Hindi',
  'Goyal',
  '6',
  'Computer',
  'Fun With Coding',
  'Goyal',
  '7',
  'Drawing',
  'Canvas C',
  'Goyal',
  '8',
  'GK',
  'General Knowledge Times',
  'Goyal',
  '9',
  'Aptitude',
  'Know Your Aptitude',
  'Goyal'
]
export const sevenData = [
  '1',
  'English',
  'English Cruise',
  'S.Chand',
  'English Comprehension ',
  'S.Chand',
  'English Hand writing',
  'English-3',
  'Firefly',
  '2',
  'Maths',
  'New Learning Composite Maths',
  'S.Chand',
  '3',
  'EVS',
  'The Blue Planet',
  'Goyal',
  '4',
  'Tamil',
  'Tamil Samacheer',
  'Tamil Ilakkanam',
  'Tamil Amuthu Ilakkana Payirchi',
  'Tamil Handwriting',
  'Tamil-3',
  'Firefly',
  '5',
  'Hindi',
  'Goyal',
  '6',
  'Computer',
  'Fun With Coding',
  'Goyal',
  '7',
  'Drawing',
  'Canvas C',
  'Goyal',
  '8',
  'GK',
  'General Knowledge Times',
  'Goyal',
  '9',
  'Aptitude',
  'Know Your Aptitude',
  'Goyal'
]
export const eightData = [
  '1',
  'English',
  'English Cruise',
  'S.Chand',
  'English Comprehension ',
  'S.Chand',
  'English Hand writing',
  'English-3',
  'Firefly',
  '2',
  'Maths',
  'New Learning Composite Maths',
  'S.Chand',
  '3',
  'EVS',
  'The Blue Planet',
  'Goyal',
  '4',
  'Tamil',
  'Tamil Samacheer',
  'Tamil Ilakkanam',
  'Tamil Amuthu Ilakkana Payirchi',
  'Tamil Handwriting',
  'Tamil-3',
  'Firefly',
  '5',
  'Hindi',
  'Goyal',
  '6',
  'Computer',
  'Fun With Coding',
  'Goyal',
  '7',
  'Drawing',
  'Canvas C',
  'Goyal',
  '8',
  'GK',
  'General Knowledge Times',
  'Goyal',
  '9',
  'Aptitude',
  'Know Your Aptitude',
  'Goyal'
]
export const nineData = [
  '1',
  'English',
  'English Cruise',
  'S.Chand',
  'English Comprehension ',
  'S.Chand',
  'English Hand writing',
  'English-3',
  'Firefly',
  '2',
  'Maths',
  'New Learning Composite Maths',
  'S.Chand',
  '3',
  'EVS',
  'The Blue Planet',
  'Goyal',
  '4',
  'Tamil',
  'Tamil Samacheer',
  'Tamil Ilakkanam',
  'Tamil Amuthu Ilakkana Payirchi',
  'Tamil Handwriting',
  'Tamil-3',
  'Firefly',
  '5',
  'Hindi',
  'Goyal',
  '6',
  'Computer',
  'Fun With Coding',
  'Goyal',
  '7',
  'Drawing',
  'Canvas C',
  'Goyal',
  '8',
  'GK',
  'General Knowledge Times',
  'Goyal',
  '9',
  'Aptitude',
  'Know Your Aptitude',
  'Goyal'
]
export const kgData = ['Kreedo Montessori Books Full Set']

export const oneArray = [
  { name: 'First', list: firstData },
  { name: 'Second', list: secondData },
  { name: 'Third', list: thirdData },
  { name: 'Fourth', list: fourthData },
  { name: 'Fifth', list: fifthData },
  { name: 'Sixth', list: sixData },
  { name: 'Seventh', list: sevenData },
  { name: 'Eighth', list: eightData },
  { name: 'Ninth', list: nineData },
  { name: 'KG', list: kgData }
]